deployment: &deployment
  filters:
    branches:
      only:
        - main
version: 2.1
orbs:
  node: circleci/node@3.0.0
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@1.0.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: npm install
          command: |
            npm install
      - persist_to_workspace:
          root: .
          paths:
            - ./node_modules
workflows:
  node-deploy:
    jobs:
      - build:
          <<: *deployment
      - RequestApproval:
          <<: *deployment
          type: approval
          requires:
            - build
      - eb/deploy:
          <<: *deployment
          context:
            - Production
          environment-name: thumbnail-generator
          requires:
            - RequestApproval
